export interface CityData {
  intro: string;
  neighborhoods: string;
  foodList: string;
  transport: string;
  itinerary: string;
  budget: string;
  mistakes: string;
  faq: { q: string; a: string }[];
}

export const cityData: Record<string, CityData> = {
  tokyo: {
    intro: "Cuando llegué a Tokio por primera vez, sentí que la ciudad no paraba de latir ni un segundo. Es enorme, limpísima y tan ordenada que parece sacada de otro planeta. No es un destino para buscarlo todo en un día: Tokio se vive con calma, barrio a barrio, y recompensa a quien se pierde entre sus calles. Es perfecta para quien quiere cultura, tecnología, gastronomía y compras sin aburrirse jamás. Si es tu primer viaje a Japón, empieza aquí y deja que la ciudad te sorprenda a cada esquina.",
    neighborhoods: "**Shinjuku:** el caos en su máxima expresión, con el barrio de Kabukicho y las vistas gratis desde el edificio del Gobierno Metropolitano, abierto hasta las 22:00. **Shibuya:** el cruce más famoso del mundo y el mirador Shibuya Sky, con entrada de 2.000¥. **Asakusa:** el Tokio tradicional junto al templo Senso-ji, abierto 24 horas y con la calle Nakamise llena de puestos. **Ginza:** elegancia y tiendas de lujo, con el edificio de la manzana 12 de diseño único. **Akihabara:** el paraíso del anime y la electrónica, con tiendas de hasta 10 plantas. **Harajuku:** la moda juvenil de Takeshita Street y el santuario Meiji-jingu justo al lado.",
    foodList: "**Ramen Ichiran** en Shibuya (1.000 a 1.300¥): te sirven en un cubículo individual y eliges tú la intensidad del caldo. **Gyukatsu Motomura** (1.900¥): carne de ternera rebozada que terminas de cocinar en una plancha de piedra. **Sushi** en Sushiro, una cinta transportadora donde cada plato cuesta entre 100 y 500¥. **Tonkatsu** en un restaurante tipo Maisen (1.600¥) o en cualquier planta de comida de un centro comercial. **Takoyaki** en un puestecillo de Asakusa (600¥ por 6 bolas). **Café en un maid cafe** de Akihabara, una experiencia curiosa que cuesta unos 1.500¥ la hora.",
    transport: "En Tokio funciona todo con las tarjetas Suica o Pasmo, que cargas en cualquier máquina de la estación con efectivo o tarjeta. Cada viaje cuesta entre 180 y 350¥ según la distancia, y sirven también en autobús y en muchas tiendas de conveniencia. El metro y el JR se gestionan con la misma tarjeta, no necesitas comprar billete por trayecto. Si piensas hacer viajes largos a otras ciudades, valora el JR Pass nacional, pero para moverte solo por Tokio no compensa. Consejo: recarga unos 2.000¥ al día y devuelve la tarjeta al final para recuperar el depósito.",
    itinerary: "**Día 1 - Mañana:** Empieza en el templo Senso-ji de Asakusa, que abre a las 6:00, para verlo sin multitudes. Recorre la calle Nakamise y compra unos senbei de postre. **Día 1 - Tarde:** Salta al barrio de Ginza y visita el edificio de la manzana 12. Después cruza al parque Yoyogi y al santuario Meiji-jingu antes de su cierre, sobre las 17:00. **Día 1 - Noche:** Cena ramen Ichiran en Shibuya y sube a Shibuya Sky para ver el cruce iluminado (2.000¥). **Día 2 - Mañana:** Pasa la mañana en el mercado exterior de Tsukiji, desayunando sushi y tamagoyaki en los puestos que abren desde las 5:00. **Día 2 - Tarde:** Dedica la tarde a Harajuku y Takeshita Street, y termina en el cruce de Shibuya al atardecer. **Día 3 - Mañana:** Visita Akihabara y sus tiendas de electrónica y anime. **Día 3 - Tarde:** Recorre Ueno, con su gran parque y museos, o haz una escapada a Kamakura en tren de 1 hora. Cena cerca de tu hotel y descansa para la última mañana.",
    budget: "**Económico:** 8.000 a 10.000¥ (50 a 65€) al día con cápsula o dormitorio compartido (3.000 a 4.000¥), ramen o bento del conbini (1.000¥) y transporte con Suica (500 a 1.000¥). **Medio:** 15.000 a 20.000¥ (95 a 130€) con hotel business (8.000 a 12.000¥), restaurantes de cinta o izakaya y alguna entrada de pago. **Alto:** 30.000¥ (195€) o más con hotel céntrico y cenas de calidad. El alojamiento es lo que más pesa en el presupuesto: reserva con meses de antelación porque en temporada alta se dispara.",
    mistakes: "1. **No recargar la Suica por adelantado:** llegas a la cola del torniquete en hora punta y pierdes tiempo. 2. **Ir a Senso-ji a mediodía:** las multitudes lo hacen agobiante, ve a primera hora. 3. **Comer siempre en cadenas:** Tokio tiene miles de restaurantes con platos de 1.000¥ espectaculares escondidos en plantas superiores. 4. **Querer verlo todo:** intentar cubrir diez barrios en un día solo da cansancio, elige dos o tres. 5. **Olvidar reservar Shibuya Sky:** se agota rápido, compra la entrada unos días antes. 6. **Cambiar dinero en el aeropuerto:** las comisiones son altas, saca en cajeros o paga con tarjeta sin comisiones.",
    faq: [
      { q: "¿Cuántos días necesito en Tokio?", a: "Con 4 a 5 días completos ves lo esencial sin agobios. Con 3 días aprietas, y si tienes más, aprovecha para excursiones a Kamakura o Nikko. La ciudad es enorme y merece un ritmo tranquilo." },
      { q: "¿Merece la pena el JR Pass para Tokio?", a: "Para moverte solo por Tokio no compensa, porque los trayectos cuestan entre 180 y 350¥. Solo renta si viajas a Kioto, Osaka u otras ciudades en el mismo viaje. La Suica o Pasmo es suficiente para la ciudad." },
      { q: "¿Tokio es caro?", a: "Menos de lo que parece: una comida completa sale por 1.000¥ (6,5€) y el transporte por viaje cuesta 200¥ de media. El alojamiento es el gasto fuerte, sobre todo en temporada alta. Con 10.000¥ diarios vives dignamente." }
    ]
  },
  kyoto: {
    intro: "Cuando llegué a Kioto, el tiempo pareció ir más despacio. Las calles de madera, los templos con jardines de musgo y el sonido de los gongs me hicieron entender por qué es el corazón cultural de Japón. No es una ciudad para correr: cada templo pide silencio y tiempo. Es perfecta para quien busca tradición, arte y tranquilidad, aunque en temporada alta las multitudes complican esa paz. Si quieres sentir el Japón clásico, esta es tu parada obligada. Me quedé tres días y sentí que me había quedado corta.",
    neighborhoods: "**Gion:** el barrio de las geishas, con calles de madera como Hanami-koji y la posibilidad de verlas al anochecer. **Higashiyama:** el camino entre el templo Kiyomizu-dera y Yasaka, ideal a pie y con tiendas de artesanía. **Arashiyama:** el bosque de bambú y el puente Togetsukyo, mejor a primera hora o al atardecer. **Ponto-cho:** el callejón de izakayas junto al río Kamo, perfecto para cenar en sus terrazas. **Nishiki Market:** el mercado cubierto, abierto de 9:00 a 18:00, para probar dulces y pescado fresco. **Fushimi Inari:** el sendero de los mil torii rojos, abierto 24 horas y mucho más bonito sin gente.",
    foodList: "**Yudofu o tofu hervido** en un restaurante tradicional de Arashiyama (2.000 a 3.000¥), el plato más purista de Kioto. **Kyo-kaiseki** en Kikunoi, un restaurante con estrellas Michelin, donde el menú mínimo ronda los 20.000¥. **Soba fría** en un puesto de Higashiyama (900¥), perfecta para el calor del verano. **Bocados del mercado:** tamago, fideos y dulces en Nishiki Market por 300 a 800¥ cada uno. **Matcha y wagashi** en una casa de té de Gion (1.200¥). **Okonomiyaki estilo Kansai** en una taberna de Ponto-cho (1.300¥).",
    transport: "Kioto no tiene un metro extenso, así que la mejor combinación es autobús urbano y tren. El pase de autobús de un día cuesta 700¥ y compensa si haces tres o más trayectos, ya que cada viaje suelto vale 230¥. El tren JR conecta con Fushimi Inari y Arashiyama por 140 a 240¥ por trayecto. La tarjeta ICOCA o Suica funciona en todo. Consejo: alquila una bicicleta por 1.000 a 1.500¥ al día para recorrer Higashiyama sin esperas. Evita el taxi, es caro y los atascos en temporada alta son constantes.",
    itinerary: "**Día 1 - Mañana:** Sube al templo Kiyomizu-dera desde la calle de tiendas de Higashiyama, llegando antes de las 9:00 para evitar masas. **Día 1 - Tarde:** Baja caminando por Ninenzaka y Sanenzaka hacia Yasaka-jinja y el barrio de Gion. Pasea Hanami-koji al atardecer, cuando es más fácil ver a alguna geisha. **Día 1 - Noche:** Cena okonomiyaki en una taberna de Ponto-cho y da un paseo por el río Kamo. **Día 2 - Mañana:** Toma el tren a Fushimi Inari y recorre el sendero de los mil torii hasta la cima, unas dos horas sin apenas subida dura. **Día 2 - Tarde:** Ve en tren a Arashiyama, camina por el bosque de bambú y cruza el puente Togetsukyo antes de las 15:00. **Día 2 - Noche:** Cena yudofu en un restaurante junto al río. **Día 3 - Mañana:** Recorre el jardín de Ryoan-ji con su famoso jardín de piedras y el Palacio Imperial. **Día 3 - Tarde:** Despídete en Nishiki Market probando dulces y pescado hasta las 18:00.",
    budget: "**Económico:** 9.000 a 11.000¥ (60 a 72€) al día con albergue (3.500¥), soba o bento (1.000¥) y pase de autobús (700¥). **Medio:** 15.000 a 20.000¥ (95 a 130€) con ryokan sencillo o hotel (10.000¥) y una cena de 2.500¥. **Alto:** desde 25.000¥ (160€) con ryokan con onsen y cena kaiseki incluida. El alojamiento en Kioto escasea en temporada alta, así que reserva con tres o cuatro meses de antelación. Las entradas a los templos cuestan de media 400 a 600¥ cada una, llévalo en cuenta.",
    mistakes: "1. **Subir a Kiyomizu-dera a mediodía:** la cola y el calor lo convierten en sufrimiento, ve a las 8:30. 2. **Usar el autobús para distancias cortas:** entre templos cercanos compensa caminar, el bus se atasca en temporada alta. 3. **Saltarse Fushimi Inari:** es gratis y de los lugares más bonitos de Japón, no lo aplaces. 4. **Reservar alojamiento tarde:** los ryokan se llenan meses antes y los precios se triplican. 5. **Esperar geishas garantizadas:** se ven, pero con paciencia y respeto, no hagas fotos de cerca sin permiso. 6. **No probar el matcha en Gion:** es de los mejores del país y cuesta poco.",
    faq: [
      { q: "¿Cuántos días necesito en Kioto?", a: "Con 3 días completos ves lo esencial, y con 4 puedes incluir Nara o Fushimi Inari con calma. Con solo 1 o 2 días irás corriendo. Es de las ciudades donde más compensa dedicar tiempo." },
      { q: "¿Merece la pena el pase de autobús de un día?", a: "Si haces tres o más trayectos sí, cuesta 700¥ y cada viaje suelto 230¥. Combínalo con el tren para Fushimi Inari y Arashiyama. El metro y el tranvía no cubren toda la ciudad." },
      { q: "¿Kioto es caro?", a: "Las entradas a los templos y el alojamiento son lo más caro, pero la comida se mantiene en 1.000 a 1.500¥. Un ryokan con cena puede superar los 30.000¥ por noche. Reserva con tiempo para controlar el presupuesto." }
    ]
  },
  osaka: {
    intro: "Cuando llegué a Osaka, sentí que por fin podía respirar. Es la ciudad más desenfadada de Japón, famosa por su gente bromista, su comida callejera y su energía nocturna. No tiene el peso cultural de Kioto ni la inmensidad de Tokio, pero tiene un encanto propio que engancha. Es perfecta para amantes de la gastronomía y de la vida nocturna, y una base ideal para explorar Kioto, Nara y Kobe. Si Japón te parece serio y estricto, Osaka te demostrará lo contrario desde la primera cena.",
    neighborhoods: "**Dotonbori:** la calle más famosa, con el anuncio del corredor Glico y cientos de restaurantes abiertos hasta tarde. **Shinsaibashi:** el eje comercial al lado de Dotonbori, perfecto para comprar hasta las 20:30. **Namba:** el corazón gastronómico, con el mercado Kuromon y miles de puestos. **Umeda:** la zona de negocios y la estación más grande, con el jardín en la azotea del edificio Umeda Sky (1.500¥). **Shinsekai:** el barrio retro con la torre Tsutenkaku y kushikatsu por todas partes. **Tennoji:** la zona del templo Shitennoji y el parque, mucho más tranquila.",
    foodList: "**Okonomiyaki** en un local de Namba (1.300¥), la tortita salada con repollo y cerdo que se cocina delante de ti. **Takoyaki** en un puesto de Dotonbori (700¥ por 8), bolas de pulpo con salsa dulce. **Kushikatsu** en Shinsekai, brochetas rebozadas desde 100¥. **Sushi** en Sushiro o Kura Sushi, cintas transportadoras con platos de 120 a 300¥. **Ramen tonkotsu** en Ippudo, desde 980¥. **Fugu** en un restaurante especializado de Namba, desde 4.000¥ si te atreves con el pez globo.",
    transport: "Osaka tiene un metro excelente y barato: cada trayecto cuesta entre 190 y 290¥. La tarjeta ICOCA funciona en metro, autobús y tren, y también la aceptan en Kioto y Nara. Si haces más de tres viajes al día, compra el pase de un día, 590¥ en fin de semana y 820¥ entre semana. Para ir a Kioto, el tren JR tarda 30 minutos y cuesta 580¥. El pase Osaka Amazing te da metro ilimitado y descuentos en atracciones por 2.800¥. Consejo: muévete a pie entre Dotonbori y Namba, están pegados y el paseo es parte de la experiencia.",
    itinerary: "**Día 1 - Mañana:** Empieza en el mercado Kuromon de Namba probando pulpo, dulces y marisco fresco hasta las 11:00. **Día 1 - Tarde:** Camina hasta Dotonbori y recorre el canal hasta el famoso anuncio Glico. Sigue por Shinsaibashi para comprar. **Día 1 - Noche:** Cena takoyaki y okonomiyaki en Namba y pasea entre los letreros de neón hasta la medianoche. **Día 2 - Mañana:** Sube al castillo de Osaka y recorre su museo interior, entrada 600¥, con hora y media es suficiente. **Día 2 - Tarde:** Explora Shinsekai y su torre Tsutenkaku, y prueba el kushikatsu. **Día 2 - Noche:** Sube al Umeda Sky Building al atardecer para ver la puesta de sol sobre la ciudad. **Día 3 - Mañana:** Escápate a Kioto o Nara en tren de 30 a 45 minutos y vuelve por la tarde. **Día 3 - Tarde:** Termina en el barrio de Tennoji, tranquilo y con el templo Shitennoji, uno de los más antiguos de Japón.",
    budget: "**Económico:** 7.000 a 9.000¥ (45 a 58€) al día con cápsula o albergue (3.000¥), comida callejera (1.500¥) y metro (500¥). **Medio:** 12.000 a 16.000¥ (78 a 105€) con hotel business (8.000¥), cenas en izakaya y algún mirador. **Alto:** desde 25.000¥ (160€) con hoteles junto a Dotonbori y cenas de sushi de calidad. Osaka es más barata que Tokio para dormir, así que es una gran base si viajas con poco presupuesto. La comida callejera es de lo más rentable de Japón: con 2.000¥ cenas de sobra.",
    mistakes: "1. **Ir a Dotonbori con hambre y sin plan:** la multitud es abrumadora, elige restaurante antes o haz cola con paciencia. 2. **Dormir en Kioto y volver cada noche:** dormir en Osaka sale más barato y los trenes de madrugada se cortan pronto. 3. **Perderse el castillo:** cuesta 600¥ y merece mucho la pena, no es solo la torre. 4. **Pagar de más en Kuromon:** muchos puestos duplican el precio de la calle, pregunta siempre antes. 5. **Quedarse solo en Dotonbori:** Shinsekai y Tennoji tienen su propia magia y menos turistas. 6. **No probar el takoyaki recién hecho:** se enfría en minutos y pierde todo su encanto.",
    faq: [
      { q: "¿Cuántos días necesito en Osaka?", a: "Con 2 días completos ves la ciudad, y con 3 puedes añadir Kioto o Nara. Muchos la usan de base y solo le dedican tardes, pero merece una jornada entera por su comida y ambiente. Si te gusta la noche, un día extra no sobra." },
      { q: "¿Merece la pena Osaka si ya voy a Tokio?", a: "Sí, porque su ambiente y su comida son distintos a todo lo demás. Es el mejor sitio para cenar barato y vivir el Japón más relajado. Además está a media hora de Kioto, así que funciona como base perfecta." },
      { q: "¿Osaka es caro?", a: "Es de las grandes ciudades más económicas de Japón. Dormir cuesta menos que en Tokio y la comida callejera es baratísima. Con 9.000 a 12.000¥ al día vives muy cómodo." }
    ]
  },
  hiroshima: {
    intro: "Cuando llegué a Hiroshima no sabía muy bien qué esperar. Encontré una ciudad luminosa, tranquila y rebosante de vida, rodeada de ríos y canales. El Parque de la Paz es un lugar que te remueve por dentro, pero Hiroshima es mucho más que su historia: tiene una gastronomía genial, un puerto precioso y la isla de Miyajima a media hora. Es perfecta para quien busca reflexión, naturaleza y un Japón sin aglomeraciones. En dos días te deja huella para siempre, y no es una frase hecha.",
    neighborhoods: "**Parque de la Paz:** el centro emocional de la ciudad, con el Museo Memorial (200¥) y la Cúpula de la Bomba Atómica, de visita obligada. **Hondori:** la calle comercial cubierta, con tiendas y restaurantes hasta las 20:00. **Nagarekawa:** el barrio de la marcha y los bares, lleno de vida por la noche. **Miyajimaguchi:** el puerto del que sale el ferry a Miyajima, con salidas cada 15 minutos (180¥ ida). **Ujina:** la zona del puerto, tranquila y con restaurantes de pescado. **El monte Misen:** en Miyajima, al que se sube en teleférico por 1.100¥ ida y vuelta.",
    foodList: "**Okonomiyaki estilo Hiroshima:** fideos, repollo y cerdo en capas, el mejor sitio es Okonomimura (1.200 a 1.500¥), un edificio de tres pisos lleno de puestos. **Ostras frescas** a la plancha en Miyajima, desde 400¥ la unidad, o fritas por unos 900¥. **Momiji manju:** dulces de pastel de arce con relleno de anko, 300¥ por 8 en Miyajima. **Ramen de pato** en algún puesto de Hondori desde 900¥. **Anago o anguila de mar**, un manjar local que sirven en restaurantes del centro desde 2.000¥.",
    transport: "Hiroshima tiene un tranvía eléctrico clásico que cuesta entre 180 y 220¥ por trayecto. El pase de un día para el tranvía cuesta 700¥ y compensa si te mueves mucho. La tarjeta ICOCA funciona en el tranvía y en el tren, aunque no en los autobuses urbanos. Para Miyajima, ve en tren JR hasta Miyajimaguchi y toma el ferry de la compañía JR, gratis con el JR Pass, o el ferry local por 180¥. Consejo: alquila una bicicleta para recorrer la orilla del río, es plana y muy agradable.",
    itinerary: "**Día 1 - Mañana:** Ve al Parque de la Paz a primera hora, antes de las 9:00, y visita la Cúpula de la Bomba Atómica y el Museo Memorial (200¥). Dedica al menos dos horas a caminar en silencio entre los monumentos. **Día 1 - Tarde:** Pasea por el barrio de Hondori y entra en Okonomimura, el edificio de puestos donde se cocina el okonomiyaki estilo Hiroshima en capas. **Día 1 - Noche:** Cena ostras frescas en el barrio de Nagarekawa y tómate algo en sus bares. **Día 2 - Mañana:** Toma el ferry a Miyajima a primera hora y camina hasta el torii flotante de Itsukushima, que se ve mejor con marea alta. **Día 2 - Tarde:** Sube al monte Misen en teleférico (1.100¥) y baja caminando entre ciervos hasta el puerto. **Día 2 - Noche:** Vuelve a Hiroshima y cena ramen de pato en un puesto de Hondori antes de dormir.",
    budget: "**Económico:** 8.000 a 10.000¥ (52 a 65€) al día con albergue (3.500¥), okonomiyaki y conbini (1.500¥) y tranvía (500¥). **Medio:** 13.000 a 17.000¥ (85 a 110€) con hotel business (8.000¥), cena de ostras y teleférico de Miyajima. **Alto:** desde 22.000¥ (145€) con hotel con vistas al puerto y restaurantes de pescado. Miyajima tiene hostales y ryokan desde 6.000¥ por noche si quieres dormir allí, aunque la mayoría vuelve a Hiroshima. El acceso a la isla cuesta 360¥ ida y vuelta en el ferry local.",
    mistakes: "1. **Ir al museo justo al cierre:** se llena y emocionalmente agota, mejor a primera hora con tiempo. 2. **Saltarse Miyajima:** es de los paisajes más icónicos de Japón y está a 30 minutos, no te lo pierdas. 3. **Subir al monte Misen a pie en verano:** son 3 horas de cuesta, el teleférico cuesta 1.100¥ y lo merece. 4. **Comer okonomiyaki sin fideos:** el estilo de Hiroshima lleva fideos y es distinto al de Osaka, no te confundas. 5. **No mirar las mareas:** el torii flotante solo se ve bonito con marea alta, consulta la tabla antes de ir. 6. **Pensar que es solo el memorial:** la ciudad tiene gastronomía y ambiente nocturno estupendos.",
    faq: [
      { q: "¿Cuántos días necesito en Hiroshima?", a: "Con 2 días completos tienes de sobra: uno para el memorial y la ciudad, otro para Miyajima. En un solo día se puede, pero irás con prisas. Desde Osaka está a 90 minutos en tren bala, así que se puede hacer de ida y vuelta." },
      { q: "¿Merece la pena Miyajima?", a: "Totalmente, es de los lugares más bonitos de Japón y su torii flotante es único. Dedícale un día entero para poder subir al monte Misen. El ferry desde Hiroshima cuesta 180¥ y tarda 10 minutos." },
      { q: "¿Hiroshima es caro?", a: "Es más barata que Tokio o Kioto para alojarse y comer. Con 9.000 a 12.000¥ al día vives cómodo. El memorial es gratis o muy barato, así que no es un destino caro." }
    ]
  },
  nara: {
    intro: "Cuando llegué a Nara, los ciervos me esperaban a la salida de la estación como si fueran anfitriones. Es una ciudad pequeña, de casas bajas y templos enormes, y su parque central esconde algunas de las construcciones más antiguas de Japón. El Todai-ji, con su buda gigante, me dejó sin palabras. Es perfecta para una excursión de un día desde Kioto u Osaka, pero también merece una noche para ver el parque vacío. Si buscas un Japón con sabor histórico y sin estrés, esta es tu parada.",
    neighborhoods: "**Parque de Nara:** el corazón de la ciudad, con miles de ciervos sueltos y los templos principales. **Naramachi:** el antiguo barrio de mercaderes, con calles de madera y tiendas de artesanía. **Todai-ji:** el templo del Gran Buda, entrada 600¥ y una de las estructuras de madera más grandes del mundo. **Kasuga Taisha:** el santuario de los miles de faroles, con su sendero de piedra. **Horyu-ji:** a 30 minutos en tren, el templo de madera más antiguo de Japón en pie. **El monte Wakakusa:** la colina desde la que se ve el atardecer sobre toda la ciudad, con subida gratuita.",
    foodList: "**Kakinoha-zushi:** sushi envuelto en hoja de caqui, el plato tradicional de Nara, desde 800¥ en los puestos de la estación. **Udon caliente** en un local de Naramachi desde 700¥, perfecto para el frío. **Shika senbei:** las galletas para los ciervos cuestan 200¥ por paquete, recuerda que son solo para ellos. **Dulces de yuzu y anko** en las tiendas de Naramachi, unos 500¥ la porción. **Té verde y wagashi** en una casa de té junto al santuario Kasuga, 900¥. **Café y cheesecake** en alguna casa de té tradicional remodelada, 800¥.",
    transport: "Desde Kioto, Nara está a 45 minutos en tren JR y el trayecto cuesta 710¥. Desde Osaka, la línea Kintetsu llega en 35 minutos por 570¥ y la JR en 50 minutos. Una vez en la ciudad, casi todo se hace a pie: el parque y los templos están a 15 minutos de la estación. El autobús urbano cuesta 200¥ por viaje y solo lo necesitas para Naramachi o lugares alejados. Consejo: vuelve en Kintetsu si viajas desde Osaka, es la opción más rápida y barata. Con la tarjeta ICOCA o Suica no tienes que sacar billetes.",
    itinerary: "**Día 1 - Mañana:** Llega a la estación de Nara antes de las 9:00 y pasea hacia el parque, donde los ciervos te recibirán. Cruza hasta el templo Todai-ji y entra (600¥) para ver el Gran Buda, mejor a esa hora para evitar colas. **Día 1 - Tarde:** Camina hacia Kasuga Taisha y su sendero de faroles, y baja luego al barrio de Naramachi para comer un plato de udon. **Día 1 - Noche:** Sube al monte Wakakusa para el atardecer y cena en la zona de la estación. **Día 2 - Mañana:** Si te quedas otra noche, toma el tren hacia Horyu-ji (30 minutos) y visita el templo de madera más antiguo del mundo. **Día 2 - Tarde:** Vuelve a Kioto u Osaka, o pasea otra vez por el parque, ahora más vacío y con otra luz. **Día 2 - Noche:** Compra kakinoha-zushi para llevar y cierra el viaje probando los dulces de la ciudad.",
    budget: "**Económico:** 7.000 a 9.000¥ (45 a 58€) al día con albergue (3.000¥), udon y dulces (1.500¥) y tren de ida y vuelta desde Kioto (1.400¥). **Medio:** 12.000 a 15.000¥ (78 a 98€) con ryokan pequeño (7.000¥), kakinoha-zushi y una casa de té. **Alto:** desde 20.000¥ (130€) con hotel junto al parque y cenas de calidad. Como destino de excursión, el coste se reduce a tren y entradas, que rondan 500 a 800¥ cada una. Con 5.000 a 6.000¥ ves los templos principales sin problemas.",
    mistakes: "1. **Salir a la calle con comida a la vista:** los ciervos te rodean y huelen todo, guarda las bolsas en la mochila. 2. **Comprar shika senbei y correr:** acorralan a quien huye, aléjate con calma y dásela desde la mano. 3. **Dejar el Todai-ji para tarde:** las colas crecen desde las 11:00, entra temprano. 4. **Ir de vuelta el mismo día y perderte Horyu-ji:** si tienes tiempo, merece la pena el desvío. 5. **Olvidar que los templos cierran a las 17:00:** organiza el día para llegar con margen. 6. **Tratar a Nara como un mero descanso:** tiene más historia que muchas ciudades del país.",
    faq: [
      { q: "¿Cuántos días necesito en Nara?", a: "Como excursión de un día desde Kioto u Osaka es perfecto, y con medio día extra ves Horyu-ji. Si te alojas una noche, verás el parque vacío, una experiencia mágica. En dos días recorres todo con total tranquilidad." },
      { q: "¿Merece la pena ir a Nara?", a: "Sí, es uno de los mejores viajes de un día desde Kioto por su Todai-ji y sus ciervos en libertad. Los templos están entre los más antiguos de Japón y el ambiente es relajado. En media jornada ya ves lo principal." },
      { q: "¿Nara es caro?", a: "Es barato para ser un destino turístico. Las entradas cuestan 500 a 800¥ y la comida ronda 700 a 1.500¥. El único gasto grande es el tren de ida y vuelta desde Kioto, unos 1.400¥." }
    ]
  },
  kanazawa: {
    intro: "Cuando llegué a Kanazawa, pensé que era la pequeña Kioto sin multitudes que me habían prometido. Tiene el jardín más bonito de Japón, un barrio de samuráis, otro de geishas y un mercado de marisco espectacular, todo a poca distancia a pie. Es perfecta para quien busca tradición sin agobios, y una parada ideal en la ruta entre Tokio y Kioto por la costa oeste. En dos días te enamora, y su famoso pescado del mar de Japón no se olvida fácilmente.",
    neighborhoods: "**Kenroku-en:** el jardín de los seis atributos, considerado el más bello de Japón, con entrada de 320¥ y abierto de 7:00 a 18:00. **Higashi Chaya:** el barrio de las casas de té, con calles de madera y puestos de dulces. **Nishi Chaya:** el barrio de geishas más tranquilo, sin tiendas de recuerdos. **Nagamachi:** el barrio samurái, con las casas de los guerreros y sus canales. **Omicho Market:** el mercado de marisco, abierto de 9:00 a 17:30, con ostras y cangrejo fresco. **Kazue-machi:** otro barrio de casas de té junto al río Asano, perfecto al atardecer.",
    foodList: "**Sushi y sashimi en Omicho Market:** pescado del mar de Japón a precios de puerto, con sets de sushi de 1.000 a 2.000¥. **Kaisendon o bol de arroz con marisco crudo** en el mercado, desde 1.500¥. **Ostras fritas** en temporada de invierno, 500 a 800¥ por ración. **Jibuni:** un guiso tradicional de pato y verduras, plato histórico de los samuráis, desde 2.000¥. **Matcha con pan de oro comestible** en las casas de té, 1.000¥, la especialidad de la ciudad. **Cangrejo snow crab** en invierno, desde 3.000¥.",
    transport: "Kanazawa está conectada por el tren bala Hokuriku desde Tokio en 2,5 horas y desde Osaka en 2,5 horas más, con billetes de unos 7.000 a 8.000¥. Dentro de la ciudad, el autobús circular cuesta 210¥ por viaje y hay un pase de un día por 700¥ que vale la pena. Los trenes y autobuses aceptan Suica e ICOCA. La mayoría de los atractivos están a 15 o 20 minutos a pie desde la estación, así que camina siempre que puedas. Consejo: la estación es un edificio impresionante con una puerta torii gigante, no te la pierdas.",
    itinerary: "**Día 1 - Mañana:** Entra en el jardín Kenroku-en a las 8:00, cuando abre, para verlo con poca gente y la mejor luz. Camina hacia la casa de té Yukatei y el estanque Hisago-ike, los puntos más fotogénicos. **Día 1 - Tarde:** Visita el castillo de Kanazawa, con entrada gratuita, y después el barrio samurái de Nagamachi con sus canales. **Día 1 - Noche:** Pasea por el barrio de casas de té Higashi Chaya y cena sushi en el mercado Omicho o en un izakaya de los alrededores. **Día 2 - Mañana:** Recorre el mercado Omicho a primera hora para el marisco fresco y prueba un kaisendon con pescado del mar de Japón. **Día 2 - Tarde:** Descubre el barrio de Nishi Chaya, más tranquilo y auténtico, y sube al mirador de la estación al atardecer. **Día 2 - Noche:** Cena jibuni y despídete con un matcha con pan de oro comestible.",
    budget: "**Económico:** 8.000 a 10.000¥ (52 a 65€) al día con albergue (3.500¥), sushi de mercado (2.000¥) y pase de autobús (700¥). **Medio:** 13.000 a 17.000¥ (85 a 110€) con hotel business (8.000¥), kaisendon y una cena de pescado. **Alto:** desde 22.000¥ (145€) con ryokan tradicional y cena de cangrejo en invierno. El alojamiento es la clave: Kanazawa es más barata que Kioto y tiene hoteles modernos. El tren bala desde Tokio u Osaka es el mayor gasto, así que busca el JR Pass si lo combinas con otros viajes.",
    mistakes: "1. **Llegar a Kenroku-en tarde:** se llena de grupos desde las 10:00, entra a la hora de abrir. 2. **Saltarse el mercado Omicho:** es el corazón gastronómico de la ciudad y casi nadie lo menciona en las guías. 3. **Olvidar el pan de oro:** es la especialidad local, prueba el helado con copos de oro al menos una vez. 4. **Hacerlo todo en un día:** con uno solo vas corriendo, dos son la medida justa. 5. **Perderse Nishi Chaya:** Higashi Chaya se lleva todos los turistas, pero Nishi es más auténtico. 6. **No probar el pescado de invierno:** el cangrejo y las ostras de temporada son de lo mejor de Japón.",
    faq: [
      { q: "¿Cuántos días necesito en Kanazawa?", a: "Con 2 días completos tienes de sobra para jardín, barrios históricos y mercado. Como escala entre Tokio y Kioto se puede hacer en una noche, pero irás justo. Tres días solo si quieres ver Shirakawa-go, a 50 minutos." },
      { q: "¿Merece la pena Kanazawa?", a: "Sí, sobre todo si quieres el Japón clásico sin multitudes. Su jardín Kenroku-en y su mercado de marisco son únicos. Encaja perfecto en la ruta entre Tokio y Kioto gracias al tren bala Hokuriku." },
      { q: "¿Kanazawa es caro?", a: "Comparada con Kioto es bastante razonable. La comida de mercado es barata y las entradas cuestan 300 a 500¥. El tren bala para llegar es el gasto grande, no la ciudad en sí." }
    ]
  },
  fukuoka: {
    intro: "Cuando llegué a Fukuoka, descubrí que los mejores yatai del país, los puestos callejeros, se montan al anochecer junto al río Nakasu. Es una ciudad joven, cosmopolita y con un ritmo relajado, famosa por su ramen tonkotsu y su cercanía a Corea. Es la puerta de entrada del sur de Japón, perfecta para quien ya ha visto Tokio y Kioto y busca algo distinto. Con pocos turistas internacionales y mucha vida universitaria, me pareció un soplo de aire fresco.",
    neighborhoods: "**Hakata:** el barrio histórico con el santuario Kushida y la estación del tren bala, abierto de 9:00 a 17:00. **Nakasu:** la zona de los yatai, los puestos callejeros que se montan al caer la tarde junto al río. **Tenjin:** el centro comercial con cientos de tiendas y el mercado subterráneo. **Momochi:** la zona costera con la torre Fukuoka, con vistas a 234 metros por 800¥. **Ohori-koen:** el parque con su gran estanque y jardines, perfecto para pasear. **Dazaifu:** a 40 minutos en tren, el santuario Tenmangu, el más importante de Japón para estudiantes.",
    foodList: "**Ramen tonkotsu** en Ichiran, cuya casa matriz está en Fukuoka, o en una cadena local por 800 a 1.100¥. **Yatai de Nakasu:** puestos de yakitori, gyoza y ramen con platos de 300 a 600¥, una experiencia nocturna única. **Mentaiko o huevas de bacalao picantes**, la especialidad local, en tiendas desde 1.000¥. **Mizutaki:** un caldo de pollo para mojar con verduras, cena de 2.500 a 4.000¥. **Gyoza estilo Hakata**, pequeñas y crujientes, 400 a 600¥ por ración. **Kakigori y dulces** junto al lago de Ohori-koen en verano, 500 a 800¥.",
    transport: "Fukuoka tiene metro barato: cada trayecto cuesta entre 200 y 370¥. El pase de un día vale 620 a 640¥ según el día y el de dos días cuesta 1.000¥. Para Dazaifu, el tren de la línea Nishitetsu tarda 40 minutos y cuesta 400¥ ida. El aeropuerto está a solo 5 minutos de metro del centro, una maravilla. Desde Hakata salen los trenes bala hacia Hiroshima, Osaka y Tokio. Consejo: si vienes en tren bala desde Hiroshima, el trayecto cuesta unos 8.600¥ o nada con el JR Pass.",
    itinerary: "**Día 1 - Mañana:** Pasea por el santuario Kushida y el barrio histórico de Hakata, y visita el templo Tocho-ji con su gran buda de madera. **Día 1 - Tarde:** Explora Tenjin y sus calles comerciales, y pasea por la orilla del río Naka con parada en un café. **Día 1 - Noche:** Cena ramen tonkotsu en un local de Hakata y luego un yatai de Nakasu hasta las 23:00, cuando empiezan a recoger. **Día 2 - Mañana:** Escápate a Dazaifu a primera hora y visita el santuario Tenmangu, el de los estudiantes, a 40 minutos en tren desde Hakata. **Día 2 - Tarde:** Recorre el parque Ohori-koen y sube a la torre Fukuoka al atardecer para las vistas de la bahía. **Día 2 - Noche:** Cena mizutaki en un restaurante de Hakata y despídete junto al río Nakasu.",
    budget: "**Económico:** 7.000 a 9.000¥ (45 a 58€) al día con cápsula o albergue (3.000¥), ramen y yatai (2.000¥) y metro (500¥). **Medio:** 12.000 a 16.000¥ (78 a 105€) con hotel business (8.000¥), cena mizutaki y excursión a Dazaifu. **Alto:** desde 22.000¥ (145€) con hotel con vistas a la bahía y restaurantes de pescado. Fukuoka es de las grandes ciudades más baratas de Japón para dormir. El vuelo o el tren bala para llegar son los mayores gastos, pero una vez en la ciudad la comida y el transporte son económicos.",
    mistakes: "1. **Llegar a los yatai a las 20:00:** se llenan en minutos, ve sobre las 18:30 para coger sitio. 2. **No llevar efectivo a los yatai:** muchos solo aceptan yenes en mano, recarga antes. 3. **Saltarse Dazaifu:** es la excursión clásica de la ciudad y solo cuesta 400¥ el tren. 4. **Pensar que el ramen es como el de Tokio:** aquí es tonkotsu, caldo de cerdo intenso con fideos finos. 5. **Quedarse solo en la zona de Hakata:** Tenjin y la costa de Momochi tienen otra vida. 6. **No probar el mentaiko:** es el producto estrella local y solo se encuentra en esta zona.",
    faq: [
      { q: "¿Cuántos días necesito en Fukuoka?", a: "Con 2 días completos ves la ciudad y Dazaifu. Es una buena base para excursiones a Nagasaki o al monte Aso si tienes más tiempo. Como destino único del sur, 3 días son ideales." },
      { q: "¿Merece la pena el yatai de Nakasu?", a: "Muchísimo, son la imagen más típica de Fukuoka y se come desde 300¥ por plato. Ve pronto porque solo hay unos 30 puestos y se llenan. Es de las experiencias gastronómicas más auténticas de Japón." },
      { q: "¿Fukuoka es caro?", a: "Es más barata que Tokio en alojamiento y similar en comida. El ramen cuesta unos 900¥ y los puestos 300 a 600¥ por plato. Es una de las ciudades japonesas más asequibles para vivirla bien." }
    ]
  },
  nagoya: {
    intro: "Cuando llegué a Nagoya, entendí por qué pocos la eligen y casi todos se sorprenden. Es la gran ciudad industrial del centro de Japón, con un castillo imponente, templos escondidos y una gastronomía propia que no se encuentra en ningún otro sitio. Es perfecta como escala entre Tokio y Kioto, o para un viajero que quiere ver Japón sin multitudes. No tiene el glamour de otras ciudades, pero tiene un encanto honesto que me ganó. Nagoya recompensa a quien le da una oportunidad.",
    neighborhoods: "**Sakae:** el corazón comercial, con torres, tiendas y el parque de Hisaya-odori. **Nagoya-jō:** el barrio del castillo, reconstruido con madera en su interior y un jardín precioso, entrada 500¥. **Osu:** el barrio de las compras y los templos, con una calle cubierta llena de tiendas de segunda mano. **Atsuta:** el santuario Atsuta-jingu, uno de los más sagrados de Japón, con su tesoro y sus bosques. **Kanayama:** la zona de bares y restaurantes junto a la estación. **Noritake Garden:** el museo de cerámica de la marca local, gratuito y con tienda.",
    foodList: "**Hitsumabushi:** anguila a la brasa sobre arroz servida en tres formas, el plato estrella de Nagoya, desde 3.500¥ en restaurantes especializados. **Miso nikomi udon:** fideos en un guiso lento de miso rojo, desde 1.200¥. **Miso katsu:** chuleta de cerdo con salsa de miso, desde 1.100¥. **Tebasaki:** alitas de pollo fritas, el snack local perfecto, 600 a 800¥ por ración. **Taiwan ramen:** un ramen picante de origen taiwanés creado en Nagoya, desde 900¥. **Ogura toast:** tostada con pasta de judías rojas, el desayuno típico de la ciudad, 600¥.",
    transport: "Nagoya es el cruce de caminos de Japón: el tren bala la conecta con Tokio en 100 minutos y con Kioto en 35, por unos 6.600¥ el trayecto. El metro de la ciudad cuesta entre 200 y 330¥ por viaje, y el pase de un día vale 760¥ o 600¥ en fin de semana. Los autobuses urbanos también aceptan la tarjeta Suica. La mayoría de los atractivos están a 20 minutos de metro desde la estación central. Consejo: si viajas con el JR Pass, usar Nagoya como base un par de noches es una idea económica y cómoda.",
    itinerary: "**Día 1 - Mañana:** Visita el castillo de Nagoya y su interior reconstruido en madera, entrada 500¥, con hora y media es suficiente. Sube a la planta superior para las vistas del centro. **Día 1 - Tarde:** Pasea por el jardín del castillo y baja al barrio de Osu para sus tiendas de segunda mano y sus templos. **Día 1 - Noche:** Cena tebasaki y miso katsu en el barrio de Kanayama, lleno de bares locales. **Día 2 - Mañana:** Dedica la mañana al santuario Atsuta-jingu, uno de los más sagrados de Japón, y pasea por su bosque. **Día 2 - Tarde:** Descubre Noritake Garden, el museo de cerámica gratuito, y compra una pieza en su tienda. **Día 2 - Noche:** Sube al mirador del centro de Sakae para ver la ciudad iluminada y cena hitsumabushi. **Día 3 - Mañana:** Si tienes un tercer día, visita el pueblo de Inuyama y su castillo original o el museo del Toyota. **Día 3 - Tarde:** Despídete con un ogura toast y toma el tren bala hacia tu siguiente ciudad.",
    budget: "**Económico:** 7.500 a 9.500¥ (48 a 62€) al día con albergue (3.200¥), ramen y tebasaki (1.800¥) y metro (500¥). **Medio:** 12.000 a 16.000¥ (78 a 105€) con hotel business (7.500¥), una cena de miso katsu y museos. **Alto:** desde 20.000¥ (130€) con hoteles cerca de la estación y cena de anguila. Nagoya tiene precios de alojamiento más bajos que Tokio y Kioto, así que es una base excelente. El tren bala para llegar o salir es el gasto principal, a menos que tengas el JR Pass.",
    mistakes: "1. **Pasarla por alto:** mucha gente la salta y se pierde una gastronomía única. 2. **Comer solo comida internacional:** la cocina de Nagoya, como el miso katsu o el hitsumabushi, no se encuentra en el resto de Japón. 3. **Quedarse una sola noche:** el castillo, Atsuta y Osu merecen un día completo. 4. **Ir a la torre de Sakae sin mirar el horario:** cierra sobre las 22:00, pero revisa antes. 5. **No llevar la Suica cargada:** aunque el metro es barato, evitas colas. 6. **Perderse el desayuno de ogura toast:** es una tradición local que casi no aparece en las guías.",
    faq: [
      { q: "¿Cuántos días necesito en Nagoya?", a: "Con 1 día apretado o 2 completos ves lo esencial. Es ideal como parada entre Tokio y Kioto, y con un día extra se puede ir a Inuyama o a la fábrica del Toyota. La ciudad es manejable y sin aglomeraciones." },
      { q: "¿Merece la pena parar en Nagoya?", a: "Sí, si quieres descansar del turismo masivo y probar comida que no hay en otro sitio. Su castillo y el santuario Atsuta son interesantes y está perfectamente conectada. Como base de un par de noches es barata y cómoda." },
      { q: "¿Nagoya es caro?", a: "Menos que Tokio y Kioto en alojamiento y similar en comida. El metro cuesta unos 230¥ por viaje y las comidas entre 900 y 1.500¥. El tren bala para llegar es lo más caro del viaje." }
    ]
  },
  hakone: {
    intro: "Cuando llegué a Hakone, me esperaba niebla, onsen y el monte Fuji asomando entre las nubes. Es el destino de aguas termales por excelencia de Japón, a solo 90 minutos de Tokio. No tiene museos ni templos famosos, pero su lago, su teleférico sobre los cráteres y la vista del Fuji lo compensan todo. Es perfecta para una escapada de uno o dos días, para relajarse tras el ajetreo de Tokio. Aquí entendí de verdad el concepto japonés del baño termal, y no lo olvidaré.",
    neighborhoods: "**Hakone-machi:** la zona del lago Ashi con las vistas del monte Fuji y los paseos en barco pirata (1.100¥ por trayecto). **Gora:** el centro de onsen y museos, con el Hakone Open-Air Museum (1.600¥). **Owakudani:** el valle volcánico con sus aguas sulfurosas y los huevos negros cocidos al vapor, 500¥ por 5. **Miyanoshita:** un barrio tranquilo de ryokan y baños termales. **Sengokuhara:** la llanura de hierba con el Fuji al fondo. **Yumoto:** la puerta de entrada con la estación y los onsen más antiguos.",
    foodList: "**Kuro-tamago o huevos negros** de Owakudani, cocidos en aguas volcánicas, 500¥ por 5 huevos, dicen que dan siete años de vida. **Soba con yuba o piel de tofu**, especialidad de la zona, desde 1.200¥. **Onsen-manju o dulces al vapor** en los puestos de Yumoto, 400¥. **Kaiseki del ryokan:** si te alojas con pensión completa, la cena incluye pescado, tofu y verduras de la zona, incluida en los 15.000 a 30.000¥ por noche. **Unagi o anguila a la brasa** en los restaurantes junto al lago, desde 2.500¥. **Helado de leche local** en las granjas de Sengokuhara, 500¥.",
    transport: "El Hakone Free Pass cuesta 6.100¥ por dos días e incluye los trenes, el teleférico, el barco y el autobús de la zona. Para llegar desde Tokio, toma el tren Odakyu desde Shinjuku (1.350¥) o el tren bala hasta Odawara y el pase desde allí. La ruta más popular es el bucle: tren de montaña, teleférico hasta Owakudani, crucero por el lago Ashi y autobús de vuelta. Cada trayecto suelto costaría casi el doble, así que el pase compensa siempre. Consejo: consulta el clima antes de subir, con niebla no se ve nada.",
    itinerary: "**Día 1 - Mañana:** Toma el tren desde Tokio hasta Hakone-Yumoto, unas 90 minutos, y guarda el equipaje en una consigna por 600¥. **Día 1 - Tarde:** Sube el tren de montaña hacia Gora y pasa la tarde en el Hakone Open-Air Museum, con esculturas gigantes y un onsen para los pies con vistas al valle. **Día 1 - Noche:** Cena el kaiseki de tu ryokan y disfruta del baño al aire libre por la noche, cuando hay menos gente y se ven las estrellas. **Día 2 - Mañana:** Sube en teleférico hasta Owakudani y prueba los huevos negros cocidos en aguas volcánicas, luego baja hacia el lago Ashi. **Día 2 - Tarde:** Cruza el lago en barco hasta Hakone-machi y fotografía el monte Fuji si el cielo está despejado. **Día 2 - Noche:** Vuelve a Tokio en tren de 90 minutos o descansa otra noche en el onsen antes de regresar.",
    budget: "**Económico:** 12.000 a 15.000¥ (78 a 98€) al día si duermes en un albergue con onsen (6.000¥), subes con el Free Pass (6.100¥ por dos días) y comes soba y huevos negros. **Medio:** 20.000 a 30.000¥ (130 a 195€) con ryokan de gama media y pensión completa. **Alto:** desde 40.000¥ (260€) con ryokan de lujo con onsen privado y vistas al Fuji. El alojamiento es el gran gasto porque el onsen y la cena suelen ir incluidos. La comida suelta es barata si no te alojas con pensión completa.",
    mistakes: "1. **Ir con maletas grandes:** los trenes de montaña son estrechos, deja el equipaje en una consigna de Tokio. 2. **No llevar el Free Pass:** cada trayecto suelto es caro y el bucle completo cuesta más del doble con billetes sueltos. 3. **No comprobar el clima:** con niebla no verás el Fuji ni los cráteres, revisa la previsión antes de gastar. 4. **Bañarse sin ducharse antes:** es una norma de etiqueta del onsen que hay que respetar. 5. **No llevar toalla pequeña:** los onsen no siempre la facilitan. 6. **Saltarse el onsen por timidez:** es la esencia de Hakone y perderías la mitad del viaje.",
    faq: [
      { q: "¿Cuántos días necesito en Hakone?", a: "Con 2 días y una noche ves el bucle completo y disfrutas del onsen con calma. En un solo día se puede hacer el circuito, pero irás con prisas. Es la escapada perfecta de fin de semana desde Tokio." },
      { q: "¿Merece la pena el Hakone Free Pass?", a: "Sí, cuesta 6.100¥ por dos días e incluye trenes, teleférico, barco y autobús. Hacer el circuito con billetes sueltos cuesta bastante más. Además te da descuentos en muchos museos y onsen." },
      { q: "¿Hakone es caro?", a: "El alojamiento con onsen es lo caro, con precios de 15.000¥ por noche en adelante. La comida suelta es razonable y el Free Pass abarata el transporte. Si duermes en albergue, Hakone es asequible." }
    ]
  }
};
