export interface FoodData {
  type: string;
  intro: string;
  description: string;
  history: string;
  prices: string;
  bestPlaces: string;
  howToOrder: string;
  mistakes: string;
  faq: { q: string; a: string }[];
}

export interface TipData {
  topic: string;
  intro: string;
  importance: string;
  essentialInfo: string;
  commonMistakes: string;
  ourTips: string;
  realCases: string;
  faq: { q: string; a: string }[];
}

export const foodTypes: FoodData[] = [
  {
    type: "Ramen",
    intro: "Cuando probé mi primer ramen en Japón fue en una callejuela de Shinjuku, entrada la noche, con el cuello del abrigo subido y un vaso de cerveza esperándome. Ese primer caldo me dejó sin palabras. No era la sopa de sobre que había tomado en España: era umami puro, fideos al dente y un huevo marinado que cambiaba el juego. Desde entonces he probado más de cincuenta tazones y todavía persigo aquella sensación.",
    description: "El ramen es un plato de fideos de trigo servidos en un caldo caliente, típicamente acompañado de chashu (cerdo asado), huevo marinado (ajitsuke tamago), cebollino y nori. Cada región tiene su estilo: tonkotsu en Fukuoka, shoyu en Tokio, miso en Sapporo y shio en Kitakata. Se come rápido, en voz baja y con ruido de sorbo permitido. Es comida de barra, rápida y barata.",
    history: "El ramen llegó a Japón desde China a finales del siglo XIX y se popularizó tras la Segunda Guerra Mundial gracias a la ayuda de harina americana. El primer restaurante de ramen en Tokio abrió en 1910, el Rairaiken en Asakusa. En la década de los 80 los fideos instantáneos y las cadenas como Ichiran democratizaron el plato. Hoy es el plato más obsesivo de la gastronomía japonesa, con decenas de estilos regionales.",
    prices: "Un tazón básico en cadena como Ippudo o Afuri cuesta entre 850 y 1.200¥ (5-8 €). En Ichiran, el ramen clásico con kimchi y huevo ronda los 1.050-1.500¥ (7-10 €). Las barras de barrio en Tokio suelen costar 700-1.000¥ (5-7 €). Los omakase de lujo en Ginza pueden superar los 3.000¥ (20 €) pero no son la norma.",
    bestPlaces: "- **Ichiran (Tokio, Shinjuku y otros):** el templo del ramen individual, con cabinas separadas. Pedirás por máquina y no hablarás con nadie. ~1.100¥.\n- **Fuunji (Tokio, Shinjuku):** tsukemen con caldo de pescado y pollo espeso, famoso por sus líneas diarias. ~1.000¥.\n- **Afuri (Tokio, Ebisu y Harajuku):** ramen yuzu shio, ligero y aromático, perfecto para empezar. ~1.000¥.\n- **Yatai de Hakata (Fukuoka):** puestos callejeros en las calles de Nakasu con tonkotsu humeante por 700-900¥.",
    howToOrder: "En la mayoría de ramen-ya pides con máquina expendedora: introduces dinero, pulsas el botón de tu plato y entregas el ticket al camarero. Al sentarte decide el nivel de grasa, dureza de fideos y picante si lo ofrecen. Pide 'katamen' si quieres fideos más firmes. No dejes propina: está mal visto. Come con prisa y termina el caldo solo si quieres; vaciar el tazón es un gesto de respeto. Muchos locales cierran cuando agotan el caldo.",
    mistakes: "1. **Esperar la cena y encontrarte la cola:** la hora pico es 12:30-13:30 y 19:00-20:30; ve a las 11:00 o a las 14:30.\n2. **No preparar cambio:** las máquinas aceptan 1.000¥ y a veces 5.000¥, pero no billetes grandes si hay cola.\n3. **Sorber en silencio:** en Japón sorber es señal de disfrute; hacerlo sin ruido es casi un insulto culinario.\n4. **Dejar propina:** los camareros te perseguirán para devolvértela; no se deja propina.\n5. **Meterte fotos del plato durante 10 minutos:** el ramen no espera; el huevo se enfría y el fideo se pasa. Dispara rápido.",
    faq: [
      { q: "¿El ramen tiene cerdo siempre?", a: "No. Hay versiones de pollo, pescado y verduras, aunque el clásico chashu es de cerdo. Las cadenas grandes suelen tener opción sin cerdo o con tofu y menma." },
      { q: "¿Cuánto cuesta de media un ramen en Tokio en 2026?", a: "Entre 900 y 1.300¥ (6-9 €) en cadenas y barras de barrio. Los establecimientos más conocidos con cola pueden llegar a 1.500¥." },
      { q: "¿Es de mala educación no terminar el caldo?", a: "No, pero dejar el tazón vacío se considera un cumplido al cocinero. Si no puedes más, deja el caldo y agradece igualmente con 'gochisousama deshita'." }
    ]
  },
  {
    type: "Sushi",
    intro: "La primera vez que comí sushi en Japón fue en una cinta transportadora de Sushiro en Osaka, con miedo escénico y los palillos temblando. Aquel sushi de supermercado en España no tenía nada que ver con lo que llegaba por la cinta: shari templado, pescado fresco y wasabi real. Me quedé dos horas y el camarero me sonrió al verme pedir la quinta tanda. Entendí que el sushi es sencillez llevada al extremo.",
    description: "El sushi es un plato de arroz avinagrado (shari) combinado con pescado crudo, marisco o huevo. Los estilos básicos son nigiri (bocado con pescado encima), maki (rollo con alga) y gunkan (alga envuelta). En Japón se come con las manos o con palillos, siempre mojando el pescado en la salsa de soja, nunca el arroz. El jengibre limpia el paladar entre piezas y el wasabi va colocado bajo el pescado por el itamae.",
    history: "El sushi nació como conserva de pescado en arroz fermentado en el sudeste asiático y llegó a Japón hace más de mil años. El nigiri moderno, pescado crudo sobre arroz avinagrado, apareció en Edo (Tokio) a comienzos del siglo XIX como comida rápida de los trabajadores. En el siglo XX el sushi cruza el mundo y cadenas de kaiten como Sushiro lo convierten en comida popular y accesible.",
    prices: "En cadenas kaiten como Sushiro o Kura, cada plato cuesta 100-400¥ (0,70-2,70 €), por lo que una comida ronda 1.500-2.500¥ (10-17 €). Un konbini con nigiri de 8 piezas cuesta 300-500¥ (2-3,5 €). Un restaurante de barra media en Tokio cuesta 5.000-10.000¥ (33-66 €) por persona. Un omakase de lujo en Ginza puede superar los 20.000¥ (130 €).",
    bestPlaces: "- **Sushiro (todo Japón):** la cadena kaiten más popular, con platos desde 115¥. Ideal para probar de todo sin arruinarte. ~1.500-2.500¥.\n- **Genki Sushi (Tokio y Osaka):** pides por tablet y los platos llegan por cinta expresa hasta tu mesa. ~2.000¥.\n- **Mercado de Toyosu (Tokio):** el antiguo Tsukiji; barras tempraneras con toro de alta calidad por 3.000-6.000¥.\n- **Cualquier barra de estación (Kobe, Sendai):** sushi de barrio sin lujos, siempre fresco y barato.",
    howToOrder: "En las cadenas kaiten lo más fácil es pedir por tablet: eliges plato, pulsas y llega en minutos. Si estás en una barra con chef, di 'omakase' y deja que él decida, o pide piezas concretas señalando la vitrina: 'maguro', 'sake', 'tamago'. Moja solo el pescado en shoyu. Entre piezas, jengibre para limpiar. Pide 'cha' (té verde) y termina con un 'gochisousama deshita'.",
    mistakes: "1. **Mojar el arroz en soja:** empapas el shari y se deshace; moja solo el pescado, con la pieza boca abajo.\n2. **Mezclar wasabi con la soja:** en Japón el wasabi ya va en la pieza; preparar el pato de wasabi en soja es costumbre extranjera.\n3. **Comer el jengibre con el pescado:** es limpiador de paladar, no acompañamiento.\n4. **Pedir demasiado de golpe en kaiten:** los platos se enfrían; pide por tandas y no dejes sobras.\n5. **Buscar sushi de salmón ahumado:** no existe en Japón; el salmón se sirve fresco o ligeramente marinado.",
    faq: [
      { q: "¿Es seguro comer pescado crudo en Japón?", a: "Sí, la cadena de frío japonesa es estricta y el atún y el salmón pasan controles de congelación por normativa. Es más seguro que en muchos países de Europa." },
      { q: "¿Sushiro y Kura son solo para turistas?", a: "No, son la opción más popular de los japoneses en familia. Los locales las frecuentan a diario por su precio y calidad." },
      { q: "¿Cuánto debería gastar en un buen sushi en Tokio?", a: "Por 5.000-8.000¥ (33-53 €) comes un almuerzo de calidad en una barra decente. Para omakase serio presupuesta desde 15.000¥." }
    ]
  },
  {
    type: "Tempura",
    intro: "Mi primer tempura en Japón fue en un local familiar de Asakusa, cerca del templo Senso-ji. Confesé al dueño que en España el tempura me parecía un capricho grasiento y él se echó a reír. Me sirvió gamba, calabaza, berenjena y shiso, rebozado finísimo, crujiente como una hoja de papel. Lo mojé en la salsa tensuyu y aquella noche entendí por qué los japoneses lo consideran cocina de precisión.",
    description: "El tempura es un plato de marisco, verdura o pescado rebozado con una masa fina de harina y agua helada, y frito brevemente en aceite muy caliente. El resultado es una costra ligera y crujiente que no empapa el interior. Se sirve sobre arroz (tendon), con salsa tensuyu y rábano rallado, o simplemente con sal. El arte está en el control de la temperatura del aceite, clave del estilo de Edo.",
    history: "El tempura llegó a Japón con los misioneros portugueses en el siglo XVI; el nombre deriva de 'tempora', los días de abstinencia católica. En el período Edo se consolidó en Tokio como comida de puestos callejeros. La versión moderna, con masa ultra fina y aceite de sésamo, nació en restaurantes de lujo a principios del siglo XX. Hoy conviven el tendon barato y la alta cocina de omakase.",
    prices: "Un tendon (cuenco con arroz y tempura) en cadenas como Tendon Tenya cuesta 900-1.500¥ (6-10 €). Un almuerzo de tempura en restaurante de barrio cuesta 1.800-3.000¥ (12-20 €). Los locales históricos de Asakusa rondan 2.000-3.500¥ (13-23 €). Un omakase de tempura de gama alta en Ginza supera los 10.000¥ (66 €) por persona.",
    bestPlaces: "- **Tempura Tenya (Tokio y Osaka):** cadena de tendon rápido con gambas y verduras por 1.000-1.400¥. Perfecto para una comida barata y excelente.\n- **Daikokuya (Tokio, Asakusa):** el tendon clásico famoso por su gamba y huevo frito, con cola diaria. ~1.800¥.\n- **Cualquier tempura-ya de barrio en Osaka:** fritura en directo ante la barra por 2.000-3.000¥.\n- **Omakase de tempura en Ginza:** experiencia premium a partir de 10.000¥ si quieres el nivel alto.",
    howToOrder: "En un restaurante de tempura pide por menú: 'tempura teishoku' (surtido con arroz y sopa) o 'tendon' (sobre arroz). Las piezas llegan según se fríen; cómelas enseguida, mientras están crujientes. Mójalas en la salsa con rábano o espolvoréalas con sal, como prefieras. No detengas la fritura: el chef trabaja al ritmo que tú comes. Termina con el té y da las gracias.",
    mistakes: "1. **Dejar enfriar las piezas:** el tempura es de consumo inmediato; si hablas mucho, se ablanda y pierde todo el sentido.\n2. **Ahogarlo en salsa:** moja un borde, no sumerjas la pieza entera; la masa empapada se vuelve gomosa.\n3. **Pedir solo gamba:** el placer está en la variedad: calabaza, batata, shiso, pescado blanco.\n4. **Confundirlo con el rebozado de los konbini:** lo que vendes en el súper no se acerca al frito en directo.\n5. **Partir la pieza de mala manera con los palillos:** la masa es frágil; sepárala con suavidad.",
    faq: [
      { q: "¿El tempura es comida de lujo o de calle?", a: "Las dos cosas. El tendon de cadena cuesta unos 1.000¥ (7 €), pero el omakase de tempura en Ginza supera los 10.000¥ (66 €). El mismo plato, dos mundos." },
      { q: "¿Qué pescados se usan en tempura?", a: "Gamba (ebi), calamar, anchoa (kisu), besugo (tai) y anguila en algunos locales. Las verduras típicas son calabaza, berenjena, batata y hoja de shiso." },
      { q: "¿Puedo pedir tempura sin gluten?", a: "La masa clásica lleva harina de trigo y los locales suelen freír en el mismo aceite que el resto. Mejor busca locales especializados o pregunta 'komugi-nashi tempura wa arimasu ka'." }
    ]
  },
  {
    type: "Wagyu",
    intro: "Cuando mi hermana me dijo que había pagado 8.000¥ por una ración de carne en Kobe pensé que estaba loca. Hasta que me senté en una plancha de yakiniku en Osaka y vi cómo se doraba ese mármol blanco. El primer bocado se deshizo en la lengua sin masticar, con una grasa dulce que no sabía que existía. Desde entonces entiendo que el wagyu no es carne: es otra categoría.",
    description: "El wagyu son razas de vacuno japonesas (principalmente Japanese Black) criadas con métodos que producen un alto veteado de grasa intramuscular. La grasa se funde a baja temperatura, por eso la textura es tan blanda y el sabor tan mantecoso. El grado A5 es el máximo en veteado y terneza. No todo el wagyu es Kobe: hay variedades como Matsusaka, Omi, Yonezawa y Hida según la región.",
    history: "El ganado japonés se cruzó con razas europeas en el siglo XIX tras la apertura de Japón, pero fue a mediados del siglo XX cuando se seleccionaron las líneas actuales por veteado. El nombre 'wagyu' significa simplemente 'vaca japonesa'. La denominación Kobe se protegió legalmente y solo puede usarse para animales criados en la prefectura de Hyogo. Hoy el wagyu se exporta a todo el mundo.",
    prices: "El wagyu en yakiniku de cadena cuesta 2.000-4.000¥ (13-26 €) por ración de 100 gramos. Un set de degustación en Kobe con varias piezas ronda 6.000-10.000¥ (40-66 €). Un curso de teppanyaki con wagyu A5 en Ginza parte de 15.000¥ (100 €). Unos onigiri con wagyu en el súper cuestan 400-800¥ (3-5 €). El precio depende del grado y el corte.",
    bestPlaces: "- **Misono Kobe (Kobe):** el restaurante que inventó el teppanyaki de wagyu en 1945; curso de 10.000-15.000¥.\n- **Yakiniku M (Tokio, Shibuya):** cadena popular de yakiniku con wagyu a buen precio, sets desde 3.000¥.\n- **Steak Aoyama (Kobe):** almuerzo de wagyu A5 con vistas a la ciudad por 6.000-10.000¥.\n- **Cualquier supermercado de Tokio:** wagyu para cocinar en tu ryokan por 3.000-5.000¥ el paquete.",
    howToOrder: "En yakiniku eliges cortes de un menú y los asas tú en la parrilla del centro de la mesa: pocos segundos por lado, sin rebozar. En teppanyaki el chef lo hace todo y suele preguntarte el punto; en Japón lo normal es 'mediamente'. Pide una pieza de 50-100 gramos para empezar si nunca has probado el A5, porque satura rápido. Acompaña con arroz blanco y cerveza.",
    mistakes: "1. **Pedir 300 gramos de A5 para empezar:** la grasa llena muchísimo; mejor 100 gramos y subir.\n2. **Condimentarlo con salsas fuertes:** el wagyu tiene sabor delicado; la salsa de soja lo tapa entero.\n3. **Hacerlo muy hecho:** el A5 hecho pierde la grasa que es su razón de ser; templado y rosado.\n4. **Comparar precios con Europa sin mirar gramos:** 10.000¥ puede ser solo 150 gramos de A5 de primera.\n5. **Pensar que todo wagyu es Kobe:** el Kobe es una denominación protegida de Hyogo; otros wagyu son igual de buenos.",
    faq: [
      { q: "¿Cuál es la diferencia entre wagyu y Kobe?", a: "Todo el Kobe es wagyu, pero no todo el wagyu es Kobe. Kobe es una denominación de origen protegida de la prefectura de Hyogo, y solo el ganado certificado de esa zona puede usar el nombre." },
      { q: "¿Es ético el wagyu?", a: "Las granjas japonesas están reguladas y la cría es mayoritariamente en establos con dietas controladas. Es un debate como el de cualquier carne premium; si te preocupa, pregunta el origen en el restaurante." },
      { q: "¿Puedo probar wagyu sin arruinarme?", a: "Sí: en yakiniku de cadena por 2.000-4.000¥ (13-26 €) la ración, o en los bento de wagyu de supermercado por 1.000-2.000¥. La calidad es buena aunque no sea A5." }
    ]
  },
  {
    type: "Okonomiyaki",
    intro: "Mi primer okonomiyaki lo hice yo misma en una plancha de Hiroshima, guiada por la señora del local que no hablaba inglés pero tenía una paciencia infinita con mi técnica desastrosa. Eché la masa, puse repollo, cerdo, fideos y el huevo encima, y lo cubrí con salsa y mayonesa japonesa. Salir de allí con el estómago lleno y la camiseta salpicada sigue siendo uno de mis mejores recuerdos.",
    description: "El okonomiyaki es una tortilla-pizza salada hecha a la plancha con una masa base de harina y huevo, repollo rallado y los ingredientes que elijas ('okonomi' significa 'a tu gusto'). Se cubre con salsa okonomiyaki dulce y mayonesa japonesa. Hay dos grandes estilos: el de Osaka, con todo mezclado, y el de Hiroshima, con capas de masa, fideos yokisoba, repollo y huevo superpuestos.",
    history: "El okonomiyaki nace de las crepes saladas de los años 30 en Osaka y Tokio, impulsado por la baratura de la harina en la posguerra. Se llamaba 'issen yoshoku', una especie de comida occidental barata. En Hiroshima se popularizó con fideos yokisoba como comida de reconstrucción tras la bomba. Hoy es un plato emblemático de la cultura de las planchas y de las celebraciones en familia.",
    prices: "Un okonomiyaki en restaurante de Osaka cuesta 900-1.500¥ (6-10 €) por persona. Los locales de plancha con menú cerrado rondan 1.200-1.800¥ (8-12 €). En Hiroshima con fideos sumas 100-300¥ extra. Las cadenas como Chibo tienen menús degustación por 2.000-3.000¥ (13-20 €). Es de las comidas más económicas para salir de noche en Japón.",
    bestPlaces: "- **Chibo (Osaka, Dotonbori):** el nombre más conocido del okonomiyaki de Osaka, con plancha en tu mesa. ~1.500¥.\n- **Cualquier okonomiyaki-ya de callejón en Shinsekai (Osaka):** bares con historia, humo y cerveza por 1.000-1.500¥.\n- **Okonomiyaki-ya en Hiroshima (barrio de Nagarekawa):** el estilo con yokisoba superpuesto, desde 1.300¥.\n- **Mizuno (Osaka, Dotonbori):** local legendario con okonomiyaki de autor desde 1.800¥.",
    howToOrder: "En la mayoría de locales eliges la masa base y añades extras: cerdo, gambas, pulpo, queso, mochi. Si cocinas tú en la plancha, el dueño te deja la espátula y te enseña; dale la vuelta cuando esté dorado y tarda un par de minutos. Sírvelo sobre tu plato, pinta salsa con la brocha, pon mayonesa en zigzag y espolvorea alga y bonito seco. Come con la espátula, es la tradición.",
    mistakes: "1. **Pensar que se cocina solo en 2 minutos:** cada capa necesita 5-10 minutos por lado; la prisa lo deja crudo por dentro.\n2. **Aplastar con la espátula:** estrujar la masa la hace gomosa; hay que darle la vuelta entera con cuidado.\n3. **Olvidar el repollo:** es el alma del plato; pedirlo sin repollo te deja con una crepe sin gracia.\n4. **No mojar bien la plancha:** se pega y la vuelta acaba en desastre; pide aceite y espera a que esté caliente.\n5. **Condimentar antes de la salsa:** el sabor final lo dan la salsa okonomiyaki y la mayonesa; no los sustituyas.",
    faq: [
      { q: "¿Okonomiyaki y takoyaki son lo mismo?", a: "No. El okonomiyaki es una tortilla a la plancha grande; el takoyaki son bolitas pequeñas de masa con pulpo, típicas de Osaka y muy populares en los puestos callejeros." },
      { q: "¿Cuál es la diferencia entre el de Osaka y el de Hiroshima?", a: "En Osaka todo se mezcla en la masa; en Hiroshima los ingredientes van por capas, incluidos fideos yokisoba. El de Hiroshima es más contundente y lleva más relleno." },
      { q: "¿Es apto para vegetarianos?", a: "Sí, muchos locales ofrecen versión 'yasai' (verduras) y el repollo, el queso y el mochi no llevan carne. Pregunta 'yasai okonomiyaki wa arimasu ka' para la versión vegetal." }
    ]
  },
  {
    type: "Yakitori",
    intro: "Recuerdo perfectamente mi primer yakitori: una barra diminuta en un yokocho de Shibuya, humo en los ojos y un pincho de pollo con 'negima' (pollo y puerro) que sabía a brasas y carbón. El dueño lo llevaba girando sobre las ascuas con una paciencia zen. Pedí dos más, luego una cerveza, luego dos más. Aquella noche entendí que el yakitori es el alma de la noche japonesa.",
    description: "El yakitori son pinchos de pollo a la brasa (o a veces de verduras, de piel o de bacon con tomate) ensartados en brocheta y asados sobre carbón binchotan. Se sirven salados ('shio') o con salsa dulce 'tare'. Los cortes van del 'momo' (muslo) al 'hatsu' (corazón) y las partes más raras del ave. Es comida de barra, de cerveza y de conversación, siempre barata.",
    history: "El yakitori nació en el período Edo como comida de puestos callejeros con pollo de deshecho y partes que nadie quería. Tras la Segunda Guerra Mundial se popularizó gracias a la carne barata y a la urbanización. En la década de los 60 llegó el carbón binchotan, que eleva el sabor ahumado. Hoy Tokio tiene más de 3.000 locales de yakitori, desde puestos humildes a estrellas Michelin como Birdland.",
    prices: "Un pincho de yakitori en barra de barrio cuesta 100-250¥ (0,70-1,70 €). En locales de yokocho una cena con cerveza ronda 2.000-3.000¥ (13-20 €) por persona. Los restaurantes más conocidos de Ginza cobran 3.000-6.000¥ (20-40 €) por una selección. Cena completa en barra popular: 2.000-3.500¥ (13-23 €).",
    bestPlaces: "- **Torikizoku (todo Japón):** la cadena de yakitori más famosa, con todos los pinchos a 360¥ (2,40 €) y bebidas baratas. Ideal para iniciarse.\n- **Cualquier yokocho de Tokio (Omoide Yokocho en Shinjuku):** callejones llenos de humo con barras de 5 asientos y pinchos de 150-300¥.\n- **Birdland (Tokio, Ginza):** yakitori de alta gama con pollo de Kioto, menú desde 5.000¥.\n- **Iseya (Tokio, Ginza):** local histórico desde 1950 con pollo de la prefectura de Ise, menú desde 4.000¥.",
    howToOrder: "Pide por piezas individuales o por set: 'momo shio' (muslo con sal), 'negima', 'tsukune' (albóndiga), 'kawa' (piel). Di 'shio' o 'tare' para elegir entre sal y salsa. En muchos locales hay un botón de cerveza en la barra que se sirve solo. La regla es ir pidiendo de dos en dos y nunca dejar la barra vacía de conversación. Termina con 'tebasaki' (alas) y la cuenta en el mostrador.",
    mistakes: "1. **Pedir todo de golpe:** los pinchos se sirven según se asan; pedirlos todos a la vez los enfría y pierdes el punto.\n2. **Pedir solo pollo normal:** te pierdes el tsukune, el kawa y los corazones, que son los pinchos más queridos por los locales.\n3. **Usar los palillos para jugar con los pinchos:** cómelos con las manos, sin quitarlos del pincho si vas cómodo.\n4. **Ir a las 20:00 a locales pequeños:** la cola es eterna; ve a las 17:30 y disfruta antes del caos.\n5. **Sorprenderte con el 'otoshi':** casi todos los locales te cobran 300-500¥ por el aperitivo de asiento aunque no lo pidas; es normal, no un timo.",
    faq: [
      { q: "¿Cuánto cuesta una cena de yakitori en Tokio?", a: "En una barra de yokocho, 2.000-3.000¥ (13-20 €) por persona con cerveza incluida. En un restaurante de gama alta de Ginza, 5.000-10.000¥ (33-66 €)." },
      { q: "¿Qué es el 'otoshi'?", a: "Es un aperitivo de bienvenida que se sirve automáticamente en la mayoría de izakayas y locales de yakitori, y se cobra aunque no lo pidas (300-500¥). Es parte de la tradición, no una estafa." },
      { q: "¿Puedo encontrar yakitori vegetariano?", a: "Sí, los locales suelen ofrecer pinchos de shishito (pimiento verde), shiitake, bacon con tomate o queso con verduras. Pide 'yasai' para la versión vegetal." }
    ]
  }
];

export const tipTopics: TipData[] = [
  {
    topic: "Transporte en Japon",
    intro: "Cuando viajé la primera vez a Japón, el mapa de metro de Tokio me pareció un jeroglífico y casi lloro en la estación de Shinjuku, la más transitada del mundo. Pero una vez que entendí que cada línea tiene su color, su nombre y sus carteles bilingües, todo cambió. El transporte en Japón es puntual, caro y complejo, pero dominarlo te convierte en un viajero libre en vez de uno dependiente.",
    importance: "El transporte es el mayor gasto variable de cualquier viaje a Japón y el que más frustración genera. Solo un trayecto de Narita al centro de Tokio cuesta 1.000-3.000¥ (7-20 €). Un error con el JR Pass puede costarte 50.000¥ (330 €) de diferencia. Además, la mayoría de los turistas pierde tiempo por no planificar los trayectos regionales. Entender el sistema es decisivo para que el viaje no se convierta en una carrera contra el reloj.",
    essentialInfo: "Lo imprescindible: usa Google Maps o Japan Travel by Navitime para rutas exactas con precio y salida de andén. El JR Pass de 7 días cuesta unos 50.000¥ (330 €) y solo compensa si viajas entre ciudades; para un viaje solo en Tokio, no lo pagues. Las tarjetas Suica e Icoca (1.500-2.000¥ con depósito) funcionan en metro, autobús y konbini en casi todo Japón. Los billetes de shinkansen por trayecto cuestan 13.000-16.000¥ (86-106 €) en la ruta Tokio-Osaka. Los últimos trenes salen sobre 23:30-00:30; no los pierdas.",
    commonMistakes: "1. **Comprar el JR Pass para viajes de una sola ciudad:** si solo tocas Tokio o Kansai, no compensa; usa Suica y billetes sueltos.\n2. **No reservar asiento en el shinkansen en temporada alta:** en Semana Dorada o Año Nuevo, muchos trenes van completos.\n3. **Perder el último tren:** los taxis nocturnos en Tokio pueden costar 3.000-5.000¥ (20-33 €); planifica.\n4. **Usar el billete equivocado en el torno:** las puertas aceptan Suica, Icoca, PASMO y JR Pass, pero no todas las máquinas recargan igual.\n5. **No mirar si el tren es expreso o local:** un rapid te salta la mitad de las paradas y te deja lejos de tu hotel.\n6. **Activar el JR Pass el día 1:** los 7 días son consecutivos; actívalo para el día del primer shinkansen, no para la llegada.",
    ourTips: "1. **Descarga Google Maps con rutas offline:** funciona sin datos y te marca andén y precio de cada trayecto.\n2. **Compra la Suica en Apple Pay o en máquinas:** la tarjeta física requiere 500¥ de depósito; la digital se recarga en segundos.\n3. **Reserva el shinkansen con asiento 1-2 días antes en temporada alta:** gratis en la web oficial de JR con tu tarjeta.\n4. **Usa el tren local en Tokio si vas con tiempo:** cuesta 300-500¥ (2-3 €) frente a los 1.000¥ del expreso a Narita.\n5. **Camina 15 minutos antes de cambiar de estación:** Shinjuku y Umeda tienen transbordos eternos entre líneas privadas.\n6. **Lleva efectivo para máquinas antiguas:** no todas aceptan tarjeta; las recargas de Suica en estaciones pequeñas van en metálico.",
    realCases: "Una vez me quedé dormida en el último tren de Shinjuku y acabé en una estación fantasma a las 00:45; el taxi de vuelta me costó 4.500¥ (30 €), la peor compra del viaje. Un amigo se gastó 50.000¥ en un JR Pass de 7 días para quedarse cuatro en Tokio y no lo usó ni una vez; hoy siempre calcula antes. Y la mejor: el shinkansen de Kioto a Tokio salió con exactamente 0 segundos de retraso. En Japón, el tren no espera: eres tú quien debe estar en el andén.",
    faq: [
      { q: "¿Merece la pena el JR Pass en 2026?", a: "Desde la subida de precios de 2023 (50.000¥ por 7 días), solo compensa si haces al menos dos trayectos largos, como Tokio-Kioto-Hiroshima. Para rutas de una sola ciudad, no." },
      { q: "¿Qué tarjeta de transporte compro?", a: "La Suica o Icoca, que funcionan en la mayoría de ciudades y también en tiendas. Se recargan en máquinas y estaciones; valen para metro, autobús y trenes urbanos." },
      { q: "¿Puedo pagar el transporte con tarjeta bancaria?", a: "Las tarjetas Suica e Icoca se recargan con efectivo o con tarjeta en máquinas grandes. Los taxis aceptan tarjeta, pero los buses rurales a veces solo monedas." }
    ]
  },
  {
    topic: "Presupuesto para Japon",
    intro: "La primera vez que calculé el presupuesto para Japón en España pensé que sería carísimo y que tendría que elegir entre comer bien o ver templos. Error. Cuando llegué descubrí que con un konbini por 600¥, un ramen por 1.000¥ y un hostel por 3.000¥, se podía viajar con 60-80 € al día sin renunciar a nada. El truco no es gastar poco: es saber dónde gasta cada yen.",
    importance: "Japón es caro en transporte y alojamiento, pero barato en comida y entretenimiento si sabes dónde mirar. El error más común es presupuestar como si fuera París y luego no aprovechar los precios de los konbini o los almuerzos de 1.000¥. Un cálculo mal hecho puede dejarte sin margen justo cuando toca el shinkansen de 16.000¥. Con un presupuesto por bloques (transporte, alojamiento, comida, entradas) viajas sin sustos.",
    essentialInfo: "Rango real por día en 2026: hostel o dormitorio 3.000-5.000¥ (20-33 €), hotel cápsula 4.000-7.000¥ (27-46 €), ryokan con media pensión desde 20.000¥ (132 €) por persona. Comida: konbini 300-600¥, ramen 900-1.200¥, menú del día (teishoku) 1.000-1.500¥. Transporte diario en Tokio 800-1.500¥ (5-10 €) con Suica. Shinkansen Tokio-Osaka 13.000-16.000¥. Entradas: templos 300-600¥, museos 1.000-2.000¥. Un viaje de 14 días cómodo ronda 1.600-2.200 € por persona sin vuelo.",
    commonMistakes: "1. **No reservar alojamiento con antelación:** en Semana Dorada y hanami, los hostels se agotan y los precios suben un 40%.\n2. **Gastar demasiado en el traslado al aeropuerto:** los billetes de Narita al centro cuestan 3.000¥; el bus limousine por 1.300¥ (9 €) te ahorra el resto.\n3. **Retirar efectivo a lo grande:** casi todo acepta tarjeta; retirar 10.000¥ en un cajero del 7-Eleven cuesta unos 110¥ de comisión, evita retiros grandes de golpe.\n4. **Comer siempre en sitios de guía:** los locales de barrio de 1.000¥ son la mejor relación calidad-precio de Japón.\n5. **Olvidar las entradas:** onsen 1.500¥, TeamLab 2.000¥, parque de atracciones 2.500¥; suman rápido.\n6. **No usar descuentos de estudiantes o senior:** si viajas con niños o jubilados, pregunta por tarifas reducidas en trenes y museos.",
    ourTips: "1. **Fija un tope diario de efectivo:** 5.000¥ (33 €) al día en metálico y el resto con tarjeta; así evitas el cajero a diario.\n2. **Come el teishoku al mediodía:** el menú de barrio con sopa, arroz y plato principal por 1.000-1.500¥ es la mejor comida del día.\n3. **Compra agua y tentempiés en el konbini:** 150-300¥ (1-2 €) frente a los 500¥ de los vending del templo.\n4. **Reserva el ryokan con media pensión:** los desayunos japoneses incluidos cuestan menos que pagarlos sueltos.\n5. **Usa el bus nocturno para trayectos largos:** Tokio-Kioto en bus cuesta 4.000-8.000¥ (26-53 €) frente a los 16.000¥ del shinkansen.\n6. **Apunta cada gasto de 1.000¥:** se nota menos de lo que piensas; los pagos pequeños son los que deshacen el presupuesto.",
    realCases: "Una vez viajé 12 días con 90 € al día y terminé con 300 € de sobra solo por comer konbini, hostales y menús de barrio. Un amigo calculó Japón como Europa del norte, gastó 2.500 € en dos semanas y descubrió al llegar que los precios reales eran un 30% más bajos. Y la mejor anécdota: una pareja presupuestó 100 € al día y acabó gastando 70 € porque el onsen, el konbini y el ramen de barrio no son tan caros como parecen.",
    faq: [
      { q: "¿Cuánto dinero necesito por día en Japón en 2026?", a: "Con 8.000-12.000¥ (53-79 €) diarios viajas cómodo en hostal, transporte local y comida de barrio. Con 15.000-20.000¥ (99-132 €) te permites hoteles y restaurantes." },
      { q: "¿Es mejor pagar en efectivo o con tarjeta?", a: "El 80% de los sitios aceptan tarjeta, pero los mercados, puestos y máquinas de billetes quieren efectivo. Lleva 10.000-15.000¥ en metálico siempre." },
      { q: "¿Cuándo es más barato viajar a Japón?", a: "Noviembre y enero-febrero (evitando Año Nuevo) son los meses con vuelos y hoteles más baratos, con temperaturas frescas y pocas colas. El hanami de abril es carísimo." }
    ]
  },
  {
    topic: "Equipaje para Japon",
    intro: "Mi primera maleta para Japón pesaba 28 kilos y casi no podía subir las escaleras de la estación de Shinjuku. Japón es un país donde cada kilo se paga en sudor, porque hay escaleras, trenes llenos y hoteles pequeños. Hoy viajo con una maleta de 55 cm y una mochila, y lo he agradecido en cada andén. El equipaje no es un detalle: decide el ritmo de tu viaje.",
    importance: "Japón no tiene taquillas infinitas: la mayoría de las estaciones grandes tienen lockers de 400-800¥ (3-5 €) por día pero se llenan a las 9:00. En los shinkansen, las maletas que superan 160 cm de suma total necesitan plaza reservada con espacio, y sin ella no puedes subir. Y en un hotel cápsula no cabe ni una mochila grande. Maleta ligera + ropa de capas + zapatos cómodos = viaje sin arrepentimientos.",
    essentialInfo: "Maleta de 55x40x25 (cabina) o facturada pequeña: los hoteles de ciudad suelen tener cuarto de equipaje, pero las habitaciones cápsula no. Lleva zapatos que se puedan quitar fácilmente: entrarás en templos, ryokans y restaurantes sin ellos. En invierno, capas térmicas: los interiores están a 25 grados y el exterior a 0 grados. Adaptador no hace falta: los enchufes japoneses aceptan el europeo de dos clavijas sin transformador. Usa el servicio de envío de maletas (takkyubin) por 1.500-2.500¥ (10-17 €) entre ciudades.",
    commonMistakes: "1. **Meter ropa de vestir de sobra:** Japón es informal; con vaqueros, zapatillas y dos capas vas sobrado.\n2. **Zapatos incómodos:** caminarás 15.000-20.000 pasos al día; un mal zapato te arruina la semana.\n3. **No usar los lockers por miedo a pagar:** 500¥ (3 €) por deshacerte de la maleta 6 horas en Tokio es la mejor inversión del día.\n4. **Llevar adaptador de 3 clavijas:** los enchufes japoneses son de 2 clavijas tipo A; los europeos de dos patitas funcionan sin adaptador.\n5. **Facturar algo que necesitas el primer día:** lleva en cabina lo imprescindible; las conexiones largas pierden equipaje de vez en cuando.\n6. **No llevar ni una bolsa de tela:** los konbini cobran por las bolsas y los souvenirs ocupan espacio.",
    ourTips: "1. **Viaja con un 40% menos de ropa de la que piensas:** cada ciudad tiene lavanderías automáticas por 300-500¥ (2-3 €) la carga.\n2. **Usa los lockers de las estaciones grandes:** 400-800¥ (3-5 €) por horas; deja la maleta y explora libre.\n3. **Reserva el servicio takkyubin al llegar:** por 2.000¥ (13 €) tu maleta te espera en el hotel de la siguiente ciudad.\n4. **Lleva un tenugui (pañuelo) de algodón:** sirve de mantel, paño de sudor y para secar las manos en los onsen.\n5. **Empaca calzado de repuesto:** la lluvia y la nieve son frecuentes; unas chanclas ligeras te salvan.\n6. **Deja hueco para souvenirs:** el wagyu envasado, las tazas y los tenugui ocupan más de lo que crees.",
    realCases: "Una vez mi maleta de 28 kilos no cabía en el asiento del shinkansen y tuve que reservar plaza extra a última hora; desde entonces, cabina siempre. Un amigo se dejó los zapatos cómodos en casa y aguantó Kioto con mocasines: al tercer día se compró unas zapatillas japonesas por 3.000¥ (20 €). Y la anécdota favorita: una vez dejé la maleta en un locker de Osaka a las 9:00 y la recuperé 8 horas después intacta. Japón te cuida el equipaje si tú te cuidas los pies.",
    faq: [
      { q: "¿Necesito adaptador para España en Japón?", a: "No. El enchufe japonés es tipo A (dos clavijas planas) pero acepta los enchufes europeos de dos patitas redondas sin problema. Los de tres clavijas necesitan adaptador." },
      { q: "¿Cómo envío la maleta entre hoteles?", a: "Con el servicio takkyubin (Yamato Transport o Sagawa). Lo pides en el hotel o en un konbini FamilyMart, pagas 1.500-2.500¥ (10-17 €) y la maleta llega a tu próximo hotel en 24-48 horas." },
      { q: "¿Qué ropa llevo a Japón en primavera?", a: "Capas: chaqueta ligera, jersey y ropa térmica fina. Las mañanas y noches frescan (10-15 grados) pero los días pueden pasar de 20 grados. Los interiores están muy climatizados." }
    ]
  },
  {
    topic: "Frases Utiles en Japones",
    intro: "Cuando viajé la primera vez a Japón solo sabía decir 'arigatou' y 'konnichiwa'. El segundo día, en una estación perdida, me lancé con 'sumimasen, eki wa doko desu ka?' y la señora del mostrador me sonrió y me acompañó al andén. Esas cinco frases que aprendí en el avión me abrieron más puertas que cualquier app. En Japón, el esfuerzo por hablar se premia con sonrisas y ayuda.",
    importance: "El inglés funciona en Tokio y Osaka, pero fuera de ellas la cosa cambia: en Kioto, en los puestos de mercado o en los ryokans, una sonrisa y un 'sumimasen' valen más que cualquier traductor. Además, la mayoría de los japoneses mayores de 60 años no habla inglés y muchos carteles de trenes de cercanías solo están en japonés. Saber 10 frases básicas reduce el estrés, evita malentendidos y convierte una petición en una conversación.",
    essentialInfo: "Las 12 frases imprescindibles: 'Sumimasen' (disculpe, pero también gracias informal y perdón), 'Konnichiwa' (hola), 'Arigatou gozaimasu' (gracias), 'Onegaishimasu' (por favor), 'Eigo o hanashite mo ii desu ka?' (¿puede hablar inglés?), 'Doko desu ka?' (¿dónde está?), 'Ikura desu ka?' (¿cuánto cuesta?), 'O-mizu o kudasai' (agua por favor), 'Osusume wa nan desu ka?' (¿qué recomienda?), 'Toire wa doko desu ka?' (¿dónde está el baño?), 'Hai' (sí) e 'Iie' (no). Lleva siempre un papel con el nombre de tu hotel escrito en japonés.",
    commonMistakes: "1. **Hablar inglés alto y despacio:** los japoneses no son sordos; si no entienden, escríbelo o usa gestos, no subas la voz.\n2. **Usar 'anata' para decir tú:** suena brusco; en Japón se omite el sujeto y se usa el nombre o el puesto.\n3. **Traducir literalmente las frases:** 'Hai' puede significar 'le escucho' más que 'sí, tienes razón'.\n4. **Pedir the bill en lugar de 'o-kanjō o onegaishimasu':** en los bares japoneses la cuenta se pide con esa frase o se paga en el mostrador.\n5. **No usar 'sumimasen' como comodín:** es la palabra más útil de Japón: disculpa, gracias y permiso se dicen así.\n6. **Confiar solo en el traductor sin red de apoyo:** si no tienes datos, un papel con las frases clave impresas es tu salvavidas.",
    ourTips: "1. **Aprende 5 frases en el avión y úsalas el primer día:** la gente se rinde con cualquiera que intente hablar.\n2. **Imprime las frases en japonés con romaji:** para el taxi, el hotel y el restaurante; escribir funciona cuando hablar no.\n3. **Usa 'onegai shimasu' al final de cualquier petición:** es el por favor universal que hace cualquier frase más educada.\n4. **Responde 'hai' y 'arigatou gozaimasu' a cada interacción:** el ritual de cortesía vale más que la gramática.\n5. **Descarga un diccionario offline japonés-español:** funciona sin datos y tiene audio para pronunciar mejor.\n6. **Practica 'oishii desu' (está delicioso) y úsalo en cada restaurante:** verás caras de alegría que no olvidarás.",
    realCases: "Una vez, en un yatai de Fukuoka, pedí el plato señalando al de la mesa de al lado: 'sore o kudasai' (eso por favor). El cocinero se partió de risa y me regaló una bebida. Un amigo se pasó todo el viaje diciendo 'arigatou gozaimasu' a todo, incluso al ascensorista, y descubrió que en Japón eso no es exagerado, es cortesía estándar. Y la mejor anécdota: una vez el conductor del bus local me esperó porque dije 'matte kudasai' (espere, por favor) con desesperación y él se apiadó. Cinco palabras y una sonrisa cambian todo.",
    faq: [
      { q: "¿Necesito saber japonés para viajar?", a: "No, con inglés básico y gestos sobrevives, pero 10-15 frases mejoran muchísimo la experiencia. Fuera de Tokio y Osaka, el inglés desaparece." },
      { q: "¿Cómo pido la cuenta en un restaurante?", a: "Di 'O-kanjō o onegaishimasu' (la cuenta por favor) o simplemente 'o-kanjō'. En las barras y cadenas, se paga en la caja del mostrador al salir." },
      { q: "¿Qué significa 'sumimasen'?", a: "Es la palabra mágica de Japón: se usa para disculparse, para llamar al camarero, para dar las gracias en situaciones informales y para disculpar el paso en una multitud." }
    ]
  },
  {
    topic: "Conexion a Internet en Japon",
    intro: "La primera vez que viajé a Japón, aterricé en Narita sin conexión y pensé que no pasaba nada. Lo siguiente fue intentar encontrar mi hotel en Shinjuku con un mapa de papel y terminar en el lado equivocado de la estación, de madrugada, sin datos. Desde entonces, la eSIM es lo primero que compro en el avión antes de aterrizar. En Japón, estar sin internet es estar perdido, y no es una exageración.",
    importance: "Japón es un país donde la conexión se convierte en tu mapa, traductor y reserva de todo: Google Maps, el traductor, los horarios de trenes y las colas de los restaurantes dependen de datos. Sin internet pierdes tiempo y dinero: un taxi perdido cuesta 2.000¥ (13 €) cuando la solución costaba 20 € la semana. Además, el Wi-Fi gratuito público es escaso y lento fuera de Tokio. La eSIM o la pocket Wi-Fi son una decisión tan básica como el pasaporte.",
    essentialInfo: "Opciones 2026: eSIM por 2.000-4.000¥ (13-26 €) por 7-10 días con 5-20 GB, instalable en 5 minutos antes del viaje (Ubigi, Holafly, Airalo). Pocket Wi-Fi por alquiler: 3.000-5.000¥ (20-33 €) por semana, recogida en el aeropuerto, ideal para grupos de 4. La eSIM no funciona en móviles bloqueados o demasiado antiguos; la SIM física de datos cuesta 2.500-4.000¥ en tiendas como Bic Camera o en los quioscos del aeropuerto. Los konbini y cafeterías tienen Wi-Fi, pero pide la contraseña: no siempre es abierta.",
    commonMistakes: "1. **No probar la eSIM antes de volar:** si no la activas o el APN falla, aterrizas sin datos y en pánico.\n2. **Contratar gigabytes de más:** un viaje normal de 7 días consume 5-10 GB; 20 GB es tirar dinero.\n3. **Confiar en el Wi-Fi gratuito:** es escaso, lento y a veces pide registro japonés; no es tu plan B.\n4. **Llevar un móvil bloqueado a un operador:** muchas eSIM no funcionan en smartphones bloqueados; verifica el desbloqueo antes.\n5. **Perder la SIM física de datos:** se estropea en el puerto o se pierde al cambiar de tarjeta; guárdala en un sobre.\n6. **Olvidar que el tethering de la pocket Wi-Fi agota la batería:** lleva un power bank de 10.000 mAh para el grupo.",
    ourTips: "1. **Compra la eSIM online y actívala en el avión:** así aterrizas conectado, sin colas en el aeropuerto.\n2. **Elige 5-10 GB para 7 días si solo vas a usar mapas y WhatsApp:** las eSIM de 20 GB solo compensan con vídeo o teletrabajo.\n3. **Si viajas en grupo de 3-4, la pocket Wi-Fi sale más barata por persona:** 800-1.200¥ (5-8 €) al día entre todos.\n4. **Descarga los mapas offline de Google como respaldo:** si te quedas sin datos en un pueblo, sigues encontrando el camino.\n5. **Usa la Wi-Fi de los shinkansen cuando puedas:** los trenes de la línea Tokaido tienen conexión que funciona razonablemente.\n6. **Lleva un power bank:** el móvil con mapas y fotos se agota antes de comer; en Japón no hay enchufes en las calles.",
    realCases: "Una vez aterricé en Kansai a las 23:00, mi eSIM no se activó y el último bus a Osaka se fue sin mí; dormí en el aeropuerto. Desde entonces, pruebo la eSIM en el avión siempre. Un amigo se gastó 30 € en una pocket Wi-Fi de 20 GB que compartió con otros tres: salió a 7,5 € por cabeza y ni la acabaron. Y la anécdota favorita: una vez un anciano en un templo de Nara me prestó su Wi-Fi personal para pedir un taxi. La amabilidad japonesa también funciona sin internet.",
    faq: [
      { q: "¿Qué es mejor, eSIM o pocket Wi-Fi?", a: "Para 1-2 personas, eSIM (más barata y sin dispositivo extra). Para grupos de 3-4, pocket Wi-Fi. Ambas rondan 2.000-5.000¥ (13-33 €) por semana." },
      { q: "¿Cuántos GB necesito?", a: "Para 7 días con mapas, WhatsApp y fotos: 5-10 GB. Con vídeo streaming o llamadas por vídeo, sube a 15-20 GB." },
      { q: "¿Hay Wi-Fi gratis en Japón?", a: "Sí, en cafeterías como Starbucks, en algunos konbini y en las estaciones grandes, pero es lento y a veces requiere registro. No lo uses como única conexión." }
    ]
  },
  {
    topic: "Costumbres y Etiqueta en Japon",
    intro: "La primera vez que visité un santuario en Kioto me quedé paralizada: no sabía si inclinarme, aplaudir o sacarme los zapatos. Un señor mayor se dio cuenta y me hizo la reverencia a cámara lenta hasta que la copié. Ese gesto me enseñó más que cualquier guía: en Japón, la etiqueta no es protocolo vacío, es el idioma del respeto. Entenderla te abre templos, casas y corazones.",
    importance: "Japón tiene normas sociales tan sutiles que un gesto equivocado puede enfriar un trato en segundos: entrar en una casa con zapatos, señalar con el dedo o rellenar tu vaso antes que el de tu anfitrión son errores que se notan. La mayoría de los japoneses valora más un esfuerzo de cortesía que una conversación fluida. Y en 2026, con el turismo de masas, los locales agradecen especialmente a quien respeta las normas. La etiqueta no es un obstáculo: es la llave.",
    essentialInfo: "Las reglas de oro: quítate los zapatos al entrar en casas, ryokans y muchos restaurantes tradicionales (si hay tatami, siempre). En los santuarios, inclínate, da dos palmadas y una reverencia; en los templos budistas, solo reverencia. No señales con el dedo (usa la mano abierta), no comas caminando por la calle, y di 'itadakimasu' antes de comer y 'gochisousama deshita' al terminar. En el tren: silencio y sin llamadas. En el onsen, lávate sentado antes de entrar al agua y nada de toallas dentro. La propina no existe: se considera casi un insulto.",
    commonMistakes: "1. **Entrar con zapatos en un tatami:** daña la estera y es una falta grave; fíjate si hay genkan (zona de zapatos) y usa las zapatillas de interior.\n2. **Comer o beber caminando por la calle:** se considera de mala educación; párate en el sitio o busca un banco.\n3. **Rellenar tu propio vaso en una comida japonesa:** el ritual exige que llenes el vaso del otro y esperes a que llenen el tuyo.\n4. **Hablar por teléfono en el tren:** silencio absoluto; el teléfono se pone en silencio y las llamadas se hacen en el pasillo del andén.\n5. **Dejar propina en un restaurante:** el camarero correrá tras ti para devolvértela; en Japón la cuenta ya incluye el servicio.\n6. **Bañarse sin lavarse antes en el onsen:** entrar sucio en el agua es una falta imperdonable; hay duchas y taburetes para ello.",
    ourTips: "1. **Aprende la reverencia básica:** inclínate 15 grados al saludar y agradecer; con eso ya vas por delante de la mayoría de los turistas.\n2. **Lleva siempre calcetines limpios y de repuesto:** en los templos y ryokans te descalzas a todas horas.\n3. **Paga en la bandeja si te la dan en un ryokan o casa tradicional:** pon el dinero en la bandejita y espera a que te la recojan.\n4. **Di 'itadakimasu' antes de cada comida:** aunque sea en voz baja, el gesto se aprecia en todas partes.\n5. **Fotografía sin trípode en interiores de templos:** está prohibido en muchos; pregunta con 'shashin wa ok desu ka?'.\n6. **Practica el 'otsukaresama deshita' (gracias por el esfuerzo):** se usa al despedirte de quien te ha atendido, y es música para sus oídos.",
    realCases: "Una vez, en un onsen de Hakone, un anciano me dio las gracias porque me lavé antes de entrar al agua; me dijo en gestos que la mayoría de extranjeros no lo hace. Un amigo entró con zapatos en un restaurante de tatami en Kioto y el dueño se lo señaló con una sonrisa tensa; desde entonces pregunta antes de cruzar la puerta. Y la anécdota favorita: una vez una camarera de Okinawa me hizo una reverencia de vuelta tan profunda que tuve que devolvérsela. Japón es el único país donde la cortesía se convierte en deporte.",
    faq: [
      { q: "¿Tengo que quitarme los zapatos siempre?", a: "No siempre, pero sí en casas, ryokans, restaurantes con tatami y algunos templos. Si ves un genkan (escalón con zapatos fuera), esa es la señal." },
      { q: "¿Está mal dar propina en Japón?", a: "Sí, está mal visto. La cuenta incluye el servicio y los japoneses la consideran casi un insulto. Simplemente agradece con 'arigatou gozaimasu'." },
      { q: "¿Cómo me comporto en un onsen?", a: "Lávate y enjuágate bien sentado en los taburetes antes de entrar al agua. No metas la toalla en el baño, no nades ni hables alto, y no te sumerjas bajo el chorro de la cascada si hay quien espera." }
    ]
  }
];
